version: '2'

services:
  # HTTPS-ReverseProxy
  rust:
    image: blacklabelops/rust-gameserver
    container_name: rust
    ports:
      - '28015:28015'
      - '28015:28015/udp'
      - '28016:28016'
    volumes:
      - rust_data:/steamcmd/rust
    environment:
      - 'TZ=Europe/Berlin'
      - 'RUST_SERVER_STARTUP_ARGUMENTS=-batchmode -load +server.secure 1'
      - 'RUST_SERVER_IDENTITY=docker'
      - 'RUST_SERVER_SEED=12345'
      - 'RUST_SERVER_NAME=Rust Server [DOCKER]'
      - 'RUST_SERVER_DESCRIPTION=This is a Rust server running inside a Docker container!'
      - 'RUST_SERVER_URL=https://hub.docker.com/r/didstopia/rust-server/'
      - 'RUST_SERVER_BANNER_URL='
      - 'RUST_RCON_WEB=1'
      - 'RUST_RCON_PORT=28016'
      - 'RUST_RCON_PASSWORD=docker'
      - 'RUST_UPDATE_CHECKING=1'
      - 'RUST_UPDATE_BRANCH=public'
      - 'RUST_START_MODE=0'
      - 'RUST_OXIDE_ENABLED=0'
      - 'RUST_OXIDE_UPDATE_ON_BOOT=1'
      - 'RUST_SERVER_WORLDSIZE=3500'
      - 'RUST_SERVER_MAXPLAYERS=500'
      - 'RUST_SERVER_SAVE_INTERVAL=600'
    restart: unless-stopped

volumes:
  rust_data:
    external: false
